---

driver:
  name: vagrant

provisioner:
  name: chef_solo
<% if ENV['CHEF_VERSION'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
<% end %>
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6
- name: centos-7
- name: oracle-6
- name: oracle-7
- name: debian-7
- name: debian-8
- name: fedora-25
- name: fedora-26
- name: opensuse-leap-42

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
    attributes:
      kernel_modules_disabled: 1
- name: selinux_enabled
  run_list:
  - recipe[os-hardening::default]
  includes:
    - centos-7
  attributes:
    os-hardening:
      security:
        selinux_mode: enforcing
